/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedDemandRouteImport } from './routes/_authenticated/demand'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRoutesRouteRouteImport } from './routes/_authenticated/routes_/route'
import { Route as AuthenticatedMessagesRouteRouteImport } from './routes/_authenticated/messages/route'
import { Route as AuthenticatedTeamIndexRouteImport } from './routes/_authenticated/team/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedRoutesIndexRouteImport } from './routes/_authenticated/routes_/index'
import { Route as AuthenticatedOffersIndexRouteImport } from './routes/_authenticated/offers/index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages/index'
import { Route as AuthenticatedFleetIndexRouteImport } from './routes/_authenticated/fleet/index'
import { Route as AuthenticatedDemandIndexRouteImport } from './routes/_authenticated/demand/index'
import { Route as AuthSignUpFreelanceRouteImport } from './routes/auth/sign-up.freelance'
import { Route as AuthenticatedTeamInviteRouteImport } from './routes/_authenticated/team/invite'
import { Route as AuthenticatedTasksNewRouteImport } from './routes/_authenticated/tasks/new'
import { Route as AuthenticatedTasksTaskIdRouteImport } from './routes/_authenticated/tasks/$taskId'
import { Route as AuthenticatedRoutesGenerateRouteImport } from './routes/_authenticated/routes_/generate'
import { Route as AuthenticatedRoutesRouteIdRouteImport } from './routes/_authenticated/routes_/$routeId'
import { Route as AuthenticatedOffersOfferIdRouteImport } from './routes/_authenticated/offers/$offerId'
import { Route as AuthenticatedMessagesThreadIdRouteImport } from './routes/_authenticated/messages/$threadId'
import { Route as AuthenticatedFleetTruckIdRouteImport } from './routes/_authenticated/fleet/$truckId'
import { Route as AuthenticatedDemandRequestIdRouteImport } from './routes/_authenticated/demand/$requestId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemandRoute = AuthenticatedDemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutesRouteRoute =
  AuthenticatedRoutesRouteRouteImport.update({
    id: '/routes_',
    path: '/routes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRouteRoute =
  AuthenticatedMessagesRouteRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamIndexRoute = AuthenticatedTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTeamRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTasksRoute,
} as any)
const AuthenticatedRoutesIndexRoute =
  AuthenticatedRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRoutesRouteRoute,
  } as any)
const AuthenticatedOffersIndexRoute =
  AuthenticatedOffersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOffersRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMessagesRouteRoute,
  } as any)
const AuthenticatedFleetIndexRoute = AuthenticatedFleetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedFleetRoute,
} as any)
const AuthenticatedDemandIndexRoute =
  AuthenticatedDemandIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDemandRoute,
  } as any)
const AuthSignUpFreelanceRoute = AuthSignUpFreelanceRouteImport.update({
  id: '/freelance',
  path: '/freelance',
  getParentRoute: () => AuthSignUpRoute,
} as any)
const AuthenticatedTeamInviteRoute = AuthenticatedTeamInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedTeamRoute,
} as any)
const AuthenticatedTasksNewRoute = AuthenticatedTasksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedTasksRoute,
} as any)
const AuthenticatedTasksTaskIdRoute =
  AuthenticatedTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => AuthenticatedTasksRoute,
  } as any)
const AuthenticatedRoutesGenerateRoute =
  AuthenticatedRoutesGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => AuthenticatedRoutesRouteRoute,
  } as any)
const AuthenticatedRoutesRouteIdRoute =
  AuthenticatedRoutesRouteIdRouteImport.update({
    id: '/$routeId',
    path: '/$routeId',
    getParentRoute: () => AuthenticatedRoutesRouteRoute,
  } as any)
const AuthenticatedOffersOfferIdRoute =
  AuthenticatedOffersOfferIdRouteImport.update({
    id: '/$offerId',
    path: '/$offerId',
    getParentRoute: () => AuthenticatedOffersRoute,
  } as any)
const AuthenticatedMessagesThreadIdRoute =
  AuthenticatedMessagesThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedMessagesRouteRoute,
  } as any)
const AuthenticatedFleetTruckIdRoute =
  AuthenticatedFleetTruckIdRouteImport.update({
    id: '/$truckId',
    path: '/$truckId',
    getParentRoute: () => AuthenticatedFleetRoute,
  } as any)
const AuthenticatedDemandRequestIdRoute =
  AuthenticatedDemandRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => AuthenticatedDemandRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRouteRouteWithChildren
  '/routes': typeof AuthenticatedRoutesRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demand': typeof AuthenticatedDemandRouteWithChildren
  '/fleet': typeof AuthenticatedFleetRouteWithChildren
  '/offers': typeof AuthenticatedOffersRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/team': typeof AuthenticatedTeamRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/demand/$requestId': typeof AuthenticatedDemandRequestIdRoute
  '/fleet/$truckId': typeof AuthenticatedFleetTruckIdRoute
  '/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/offers/$offerId': typeof AuthenticatedOffersOfferIdRoute
  '/routes/$routeId': typeof AuthenticatedRoutesRouteIdRoute
  '/routes/generate': typeof AuthenticatedRoutesGenerateRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/team/invite': typeof AuthenticatedTeamInviteRoute
  '/auth/sign-up/freelance': typeof AuthSignUpFreelanceRoute
  '/demand/': typeof AuthenticatedDemandIndexRoute
  '/fleet/': typeof AuthenticatedFleetIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/offers/': typeof AuthenticatedOffersIndexRoute
  '/routes/': typeof AuthenticatedRoutesIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/team/': typeof AuthenticatedTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/demand/$requestId': typeof AuthenticatedDemandRequestIdRoute
  '/fleet/$truckId': typeof AuthenticatedFleetTruckIdRoute
  '/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/offers/$offerId': typeof AuthenticatedOffersOfferIdRoute
  '/routes/$routeId': typeof AuthenticatedRoutesRouteIdRoute
  '/routes/generate': typeof AuthenticatedRoutesGenerateRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/team/invite': typeof AuthenticatedTeamInviteRoute
  '/auth/sign-up/freelance': typeof AuthSignUpFreelanceRoute
  '/demand': typeof AuthenticatedDemandIndexRoute
  '/fleet': typeof AuthenticatedFleetIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/offers': typeof AuthenticatedOffersIndexRoute
  '/routes': typeof AuthenticatedRoutesIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/team': typeof AuthenticatedTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteRouteWithChildren
  '/_authenticated/routes_': typeof AuthenticatedRoutesRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demand': typeof AuthenticatedDemandRouteWithChildren
  '/_authenticated/fleet': typeof AuthenticatedFleetRouteWithChildren
  '/_authenticated/offers': typeof AuthenticatedOffersRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRouteWithChildren
  '/_authenticated/demand/$requestId': typeof AuthenticatedDemandRequestIdRoute
  '/_authenticated/fleet/$truckId': typeof AuthenticatedFleetTruckIdRoute
  '/_authenticated/messages/$threadId': typeof AuthenticatedMessagesThreadIdRoute
  '/_authenticated/offers/$offerId': typeof AuthenticatedOffersOfferIdRoute
  '/_authenticated/routes_/$routeId': typeof AuthenticatedRoutesRouteIdRoute
  '/_authenticated/routes_/generate': typeof AuthenticatedRoutesGenerateRoute
  '/_authenticated/tasks/$taskId': typeof AuthenticatedTasksTaskIdRoute
  '/_authenticated/tasks/new': typeof AuthenticatedTasksNewRoute
  '/_authenticated/team/invite': typeof AuthenticatedTeamInviteRoute
  '/auth/sign-up/freelance': typeof AuthSignUpFreelanceRoute
  '/_authenticated/demand/': typeof AuthenticatedDemandIndexRoute
  '/_authenticated/fleet/': typeof AuthenticatedFleetIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/offers/': typeof AuthenticatedOffersIndexRoute
  '/_authenticated/routes_/': typeof AuthenticatedRoutesIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/team/': typeof AuthenticatedTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/messages'
    | '/routes'
    | '/dashboard'
    | '/demand'
    | '/fleet'
    | '/offers'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/demand/$requestId'
    | '/fleet/$truckId'
    | '/messages/$threadId'
    | '/offers/$offerId'
    | '/routes/$routeId'
    | '/routes/generate'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/team/invite'
    | '/auth/sign-up/freelance'
    | '/demand/'
    | '/fleet/'
    | '/messages/'
    | '/offers/'
    | '/routes/'
    | '/tasks/'
    | '/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/demand/$requestId'
    | '/fleet/$truckId'
    | '/messages/$threadId'
    | '/offers/$offerId'
    | '/routes/$routeId'
    | '/routes/generate'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/team/invite'
    | '/auth/sign-up/freelance'
    | '/demand'
    | '/fleet'
    | '/messages'
    | '/offers'
    | '/routes'
    | '/tasks'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/messages'
    | '/_authenticated/routes_'
    | '/_authenticated/dashboard'
    | '/_authenticated/demand'
    | '/_authenticated/fleet'
    | '/_authenticated/offers'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_authenticated/demand/$requestId'
    | '/_authenticated/fleet/$truckId'
    | '/_authenticated/messages/$threadId'
    | '/_authenticated/offers/$offerId'
    | '/_authenticated/routes_/$routeId'
    | '/_authenticated/routes_/generate'
    | '/_authenticated/tasks/$taskId'
    | '/_authenticated/tasks/new'
    | '/_authenticated/team/invite'
    | '/auth/sign-up/freelance'
    | '/_authenticated/demand/'
    | '/_authenticated/fleet/'
    | '/_authenticated/messages/'
    | '/_authenticated/offers/'
    | '/_authenticated/routes_/'
    | '/_authenticated/tasks/'
    | '/_authenticated/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demand': {
      id: '/_authenticated/demand'
      path: '/demand'
      fullPath: '/demand'
      preLoaderRoute: typeof AuthenticatedDemandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routes_': {
      id: '/_authenticated/routes_'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/': {
      id: '/_authenticated/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof AuthenticatedTeamIndexRouteImport
      parentRoute: typeof AuthenticatedTeamRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/routes_/': {
      id: '/_authenticated/routes_/'
      path: '/'
      fullPath: '/routes/'
      preLoaderRoute: typeof AuthenticatedRoutesIndexRouteImport
      parentRoute: typeof AuthenticatedRoutesRouteRoute
    }
    '/_authenticated/offers/': {
      id: '/_authenticated/offers/'
      path: '/'
      fullPath: '/offers/'
      preLoaderRoute: typeof AuthenticatedOffersIndexRouteImport
      parentRoute: typeof AuthenticatedOffersRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedMessagesRouteRoute
    }
    '/_authenticated/fleet/': {
      id: '/_authenticated/fleet/'
      path: '/'
      fullPath: '/fleet/'
      preLoaderRoute: typeof AuthenticatedFleetIndexRouteImport
      parentRoute: typeof AuthenticatedFleetRoute
    }
    '/_authenticated/demand/': {
      id: '/_authenticated/demand/'
      path: '/'
      fullPath: '/demand/'
      preLoaderRoute: typeof AuthenticatedDemandIndexRouteImport
      parentRoute: typeof AuthenticatedDemandRoute
    }
    '/auth/sign-up/freelance': {
      id: '/auth/sign-up/freelance'
      path: '/freelance'
      fullPath: '/auth/sign-up/freelance'
      preLoaderRoute: typeof AuthSignUpFreelanceRouteImport
      parentRoute: typeof AuthSignUpRoute
    }
    '/_authenticated/team/invite': {
      id: '/_authenticated/team/invite'
      path: '/invite'
      fullPath: '/team/invite'
      preLoaderRoute: typeof AuthenticatedTeamInviteRouteImport
      parentRoute: typeof AuthenticatedTeamRoute
    }
    '/_authenticated/tasks/new': {
      id: '/_authenticated/tasks/new'
      path: '/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthenticatedTasksNewRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/tasks/$taskId': {
      id: '/_authenticated/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/routes_/generate': {
      id: '/_authenticated/routes_/generate'
      path: '/generate'
      fullPath: '/routes/generate'
      preLoaderRoute: typeof AuthenticatedRoutesGenerateRouteImport
      parentRoute: typeof AuthenticatedRoutesRouteRoute
    }
    '/_authenticated/routes_/$routeId': {
      id: '/_authenticated/routes_/$routeId'
      path: '/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof AuthenticatedRoutesRouteIdRouteImport
      parentRoute: typeof AuthenticatedRoutesRouteRoute
    }
    '/_authenticated/offers/$offerId': {
      id: '/_authenticated/offers/$offerId'
      path: '/$offerId'
      fullPath: '/offers/$offerId'
      preLoaderRoute: typeof AuthenticatedOffersOfferIdRouteImport
      parentRoute: typeof AuthenticatedOffersRoute
    }
    '/_authenticated/messages/$threadId': {
      id: '/_authenticated/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof AuthenticatedMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRouteRoute
    }
    '/_authenticated/fleet/$truckId': {
      id: '/_authenticated/fleet/$truckId'
      path: '/$truckId'
      fullPath: '/fleet/$truckId'
      preLoaderRoute: typeof AuthenticatedFleetTruckIdRouteImport
      parentRoute: typeof AuthenticatedFleetRoute
    }
    '/_authenticated/demand/$requestId': {
      id: '/_authenticated/demand/$requestId'
      path: '/$requestId'
      fullPath: '/demand/$requestId'
      preLoaderRoute: typeof AuthenticatedDemandRequestIdRouteImport
      parentRoute: typeof AuthenticatedDemandRoute
    }
  }
}

interface AuthenticatedMessagesRouteRouteChildren {
  AuthenticatedMessagesThreadIdRoute: typeof AuthenticatedMessagesThreadIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedMessagesRouteRouteChildren: AuthenticatedMessagesRouteRouteChildren =
  {
    AuthenticatedMessagesThreadIdRoute: AuthenticatedMessagesThreadIdRoute,
    AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  }

const AuthenticatedMessagesRouteRouteWithChildren =
  AuthenticatedMessagesRouteRoute._addFileChildren(
    AuthenticatedMessagesRouteRouteChildren,
  )

interface AuthenticatedRoutesRouteRouteChildren {
  AuthenticatedRoutesRouteIdRoute: typeof AuthenticatedRoutesRouteIdRoute
  AuthenticatedRoutesGenerateRoute: typeof AuthenticatedRoutesGenerateRoute
  AuthenticatedRoutesIndexRoute: typeof AuthenticatedRoutesIndexRoute
}

const AuthenticatedRoutesRouteRouteChildren: AuthenticatedRoutesRouteRouteChildren =
  {
    AuthenticatedRoutesRouteIdRoute: AuthenticatedRoutesRouteIdRoute,
    AuthenticatedRoutesGenerateRoute: AuthenticatedRoutesGenerateRoute,
    AuthenticatedRoutesIndexRoute: AuthenticatedRoutesIndexRoute,
  }

const AuthenticatedRoutesRouteRouteWithChildren =
  AuthenticatedRoutesRouteRoute._addFileChildren(
    AuthenticatedRoutesRouteRouteChildren,
  )

interface AuthenticatedDemandRouteChildren {
  AuthenticatedDemandRequestIdRoute: typeof AuthenticatedDemandRequestIdRoute
  AuthenticatedDemandIndexRoute: typeof AuthenticatedDemandIndexRoute
}

const AuthenticatedDemandRouteChildren: AuthenticatedDemandRouteChildren = {
  AuthenticatedDemandRequestIdRoute: AuthenticatedDemandRequestIdRoute,
  AuthenticatedDemandIndexRoute: AuthenticatedDemandIndexRoute,
}

const AuthenticatedDemandRouteWithChildren =
  AuthenticatedDemandRoute._addFileChildren(AuthenticatedDemandRouteChildren)

interface AuthenticatedFleetRouteChildren {
  AuthenticatedFleetTruckIdRoute: typeof AuthenticatedFleetTruckIdRoute
  AuthenticatedFleetIndexRoute: typeof AuthenticatedFleetIndexRoute
}

const AuthenticatedFleetRouteChildren: AuthenticatedFleetRouteChildren = {
  AuthenticatedFleetTruckIdRoute: AuthenticatedFleetTruckIdRoute,
  AuthenticatedFleetIndexRoute: AuthenticatedFleetIndexRoute,
}

const AuthenticatedFleetRouteWithChildren =
  AuthenticatedFleetRoute._addFileChildren(AuthenticatedFleetRouteChildren)

interface AuthenticatedOffersRouteChildren {
  AuthenticatedOffersOfferIdRoute: typeof AuthenticatedOffersOfferIdRoute
  AuthenticatedOffersIndexRoute: typeof AuthenticatedOffersIndexRoute
}

const AuthenticatedOffersRouteChildren: AuthenticatedOffersRouteChildren = {
  AuthenticatedOffersOfferIdRoute: AuthenticatedOffersOfferIdRoute,
  AuthenticatedOffersIndexRoute: AuthenticatedOffersIndexRoute,
}

const AuthenticatedOffersRouteWithChildren =
  AuthenticatedOffersRoute._addFileChildren(AuthenticatedOffersRouteChildren)

interface AuthenticatedTasksRouteChildren {
  AuthenticatedTasksTaskIdRoute: typeof AuthenticatedTasksTaskIdRoute
  AuthenticatedTasksNewRoute: typeof AuthenticatedTasksNewRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedTasksRouteChildren: AuthenticatedTasksRouteChildren = {
  AuthenticatedTasksTaskIdRoute: AuthenticatedTasksTaskIdRoute,
  AuthenticatedTasksNewRoute: AuthenticatedTasksNewRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedTasksRouteWithChildren =
  AuthenticatedTasksRoute._addFileChildren(AuthenticatedTasksRouteChildren)

interface AuthenticatedTeamRouteChildren {
  AuthenticatedTeamInviteRoute: typeof AuthenticatedTeamInviteRoute
  AuthenticatedTeamIndexRoute: typeof AuthenticatedTeamIndexRoute
}

const AuthenticatedTeamRouteChildren: AuthenticatedTeamRouteChildren = {
  AuthenticatedTeamInviteRoute: AuthenticatedTeamInviteRoute,
  AuthenticatedTeamIndexRoute: AuthenticatedTeamIndexRoute,
}

const AuthenticatedTeamRouteWithChildren =
  AuthenticatedTeamRoute._addFileChildren(AuthenticatedTeamRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMessagesRouteRoute: typeof AuthenticatedMessagesRouteRouteWithChildren
  AuthenticatedRoutesRouteRoute: typeof AuthenticatedRoutesRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemandRoute: typeof AuthenticatedDemandRouteWithChildren
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRouteWithChildren
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMessagesRouteRoute: AuthenticatedMessagesRouteRouteWithChildren,
  AuthenticatedRoutesRouteRoute: AuthenticatedRoutesRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemandRoute: AuthenticatedDemandRouteWithChildren,
  AuthenticatedFleetRoute: AuthenticatedFleetRouteWithChildren,
  AuthenticatedOffersRoute: AuthenticatedOffersRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthSignUpRouteChildren {
  AuthSignUpFreelanceRoute: typeof AuthSignUpFreelanceRoute
}

const AuthSignUpRouteChildren: AuthSignUpRouteChildren = {
  AuthSignUpFreelanceRoute: AuthSignUpFreelanceRoute,
}

const AuthSignUpRouteWithChildren = AuthSignUpRoute._addFileChildren(
  AuthSignUpRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
