import type { Task } from "@/shared/types/task";

export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Steel coils delivery",
    cargoDescription: "Steel coils",
    cargoType: "General",
    weightT: 18,
    originLabel: "Uman",
    destinationLabel: "Kyiv",
    distanceKm: 240,
    deadline: "2026-04-10",
    priority: "HIGH",
    status: "Assigned",
    assignedTruckId: "tr1",
  },
  {
    id: "t2",
    title: "Frozen fish transport",
    cargoDescription: "Frozen fish",
    cargoType: "Refrigerated",
    weightT: 12,
    originLabel: "Odesa",
    destinationLabel: "Lviv",
    distanceKm: 680,
    deadline: "2026-04-08",
    priority: "EMERGENCY",
    status: "Pending",
    assignedTruckId: null,
  },
  {
    id: "t3",
    title: "Electronics shipment",
    cargoDescription: "Electronics",
    cargoType: "Fragile",
    weightT: 5,
    originLabel: "Kyiv",
    destinationLabel: "Zhytomyr",
    distanceKm: 140,
    deadline: "2026-04-12",
    priority: "MEDIUM",
    status: "InTransit",
    assignedTruckId: "tr3",
  },
  {
    id: "t4",
    title: "Construction materials",
    cargoDescription: "Materials",
    cargoType: "General",
    weightT: 22,
    originLabel: "Lviv",
    destinationLabel: "Uman",
    distanceKm: 320,
    deadline: "2026-04-15",
    priority: "LOW",
    status: "Pending",
    assignedTruckId: null,
  },
  {
    id: "t5",
    title: "Medical supplies",
    cargoDescription: "Medical",
    cargoType: "General",
    weightT: 3,
    originLabel: "Zhytomyr",
    destinationLabel: "Kyiv",
    distanceKm: 130,
    deadline: "2026-04-07",
    priority: "EMERGENCY",
    status: "Delivered",
    assignedTruckId: "tr2",
  },
];
