import type { Truck } from "@/shared/types/truck";

export const mockTrucks: Truck[] = [
  {
    id: "tr1",
    name: "MAN TGX #01",
    type: "Semi",
    payloadT: 24,
    trailerId: null,
    trackerId: "gps-001",
    status: "on_road",
    locationLabel: "Uman",
  },
  {
    id: "tr2",
    name: "KAMAZ 5490 #02",
    type: "Truck",
    payloadT: 18,
    trailerId: null,
    trackerId: "gps-002",
    status: "idle",
    locationLabel: "Zhytomyr",
  },
  {
    id: "tr3",
    name: "Volvo FH #03",
    type: "Refrigerated",
    payloadT: 20,
    trailerId: null,
    trackerId: "gps-003",
    status: "on_road",
    locationLabel: "Kyiv",
  },
  {
    id: "tr4",
    name: "DAF XF #04",
    type: "Flatbed",
    payloadT: 22,
    trailerId: null,
    trackerId: "gps-004",
    status: "idle",
    locationLabel: "Lviv",
  },
  {
    id: "tr5",
    name: "MAN TGS #05",
    type: "Semi",
    payloadT: 24,
    trailerId: null,
    trackerId: "gps-005",
    status: "maintenance",
    locationLabel: "Odesa",
  },
];
